apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: "arn:aws:iam::<user_id>:root"
      username: system:node:{{<generated>}}
      groups:
        - system:bootstrappers
        - system:nodes
